In [37]:
import pandas as pd
import os
import sys
import logging
import pandas as pd
from google.cloud import bigquery
from hashlib import md5
from typing import List
import shortuuid
import numpy
import pyarrow

In [ ]:
# df = pd.read_csv("./spreadspoke_scores.csv")

# df = df[df["schedule_season"] > 1978]

# df = df.drop(columns="weather_detail")

# display(df[df["schedule_playoff"] == True])

In [99]:
DATA_DIR = "./spreadspoke_scores.csv"

PROJECT_NAME = "team-week-10"
DATASET_NAME = "nfl_sports_betting"

TABLE_METADATA = {
    "point_spread": {
        "table_name": "fct_points_spread",
        "schema": [
            bigquery.SchemaField("uuid", "string", mode="REQUIRED"),
            bigquery.SchemaField("team_fav_id", "string", mode="REQUIRED"),
            bigquery.SchemaField("home_team", "string", mode="REQUIRED"),
            bigquery.SchemaField("away_team", "string", mode="Required"),
            bigquery.SchemaField("spread_favorite", "float69", mode="Required"),
            bigquery.SchemaField("home_away_diff", "int", mode="Required"),
        ]
    },
    "over_under": {
        "table_name": "fct_over_under",
        "schema": [
            bigquery.SchemaField("uuid", "string", mode="REQUIRED"),
            bigquery.SchemaField("over_under_line", "float64", mode="NULLABLE"),
            bigquery.SchemaField("team_favorite_id", "string", mode="REQUIRED"),
            bigquery.SchemaField("team_home", "string", mode="REQUIRED"),
            bigquery.SchemaField("score_home", "int64", mode="REQUIRED"),
            bigquery.SchemaField("score_away", "int64", mode="REQUIRED"),
            bigquery.SchemaField("team_away", "string", mode="REQUIRED"),
            bigquery.SchemaField("total_score", "int64", mode="REQUIRED"),
            bigquery.SchemaField("over", "boolean", mode="REQUIRED"),
        ]
    },
    "games": {
        "table_name": "dim_games",
        "schema": [
            bigquery.SchemaField("date", "date", mode="REQUIRED"),
            bigquery.SchemaField("season", "int64", mode="REQUIRED"),
            bigquery.SchemaField("week", "string", mode="REQUIRED"),
            bigquery.SchemaField("playoff", "boolean", mode="REQUIRED"),
            bigquery.SchemaField("team_home", "string", mode="REQUIRED"),
            bigquery.SchemaField("score_home", "int64", mode="REQUIRED"),
            bigquery.SchemaField("score_away", "int64", mode="REQUIRED"),
            bigquery.SchemaField("team_away", "string", mode="REQUIRED"),
            bigquery.SchemaField("stadium", "string", mode="REQUIRED"),
            bigquery.SchemaField("temperature_F", "float64", mode="NULLABLE"),
            bigquery.SchemaField("wind_mph", "float64", mode="NULLABLE"),
            bigquery.SchemaField("humidity_%", "float64", mode="NULLABLE"),
            bigquery.SchemaField("uuid", "string", mode="REQUIRED")
        ]
    },
    "lookup_teams": {
        "table_name": "lookup_teams",
        "schema": [
            bigquery.SchemaField("team_id", "string", mode="REQUIRED"),
            bigquery.SchemaField("team_name", "string", mode="REQUIRED"),
            bigquery.SchemaField("conference_string", "string", mode="REQUIRED"),
            bigquery.SchemaField("division", "string", mode="REQUIRED"),
        ]
    }
}

logging.basicConfig(
    format='[%(levelname)-5s][%(asctime)s][%(module)s:%(lineno)04d] : %(message)s',
    level=logging.INFO,
    stream=sys.stdout
)
logger: logging.Logger = logging.getLogger("root")
logger.setLevel(logging.DEBUG)

In [3]:
dataset_id = f"{PROJECT_NAME}.{DATASET_NAME}"
client = bigquery.Client()

def create_dataset(client: bigquery.Client, dataset_id: str, location: str = "US"):
    dataset = bigquery.Dataset(dataset_id)
    dataset.location = location
    dataset = client.create_dataset(dataset, exists_ok=True)
    logger.info(f"Created dataset: {dataset.full_dataset_id}")

create_dataset(client, dataset_id)

[DEBUG][2024-01-10 13:11:15,425][_default:0255] : Checking /home/jarvismwynn/.creds/jarvis.json for explicit credentials as part of auth process...
[DEBUG][2024-01-10 13:11:15,428][_default:0255] : Checking /home/jarvismwynn/.creds/jarvis.json for explicit credentials as part of auth process...
[DEBUG][2024-01-10 13:11:15,430][opentelemetry_tracing:0066] : This service is instrumented using OpenTelemetry. OpenTelemetry or one of its components could not be imported; please add compatible versions of opentelemetry-api and opentelemetry-instrumentation packages in order to get BigQuery Tracing data.
[DEBUG][2024-01-10 13:11:15,431][retry:0282] : Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
[DEBUG][2024-01-10 13:11:15,453][requests:0185] : Making request: POST https://oauth2.googleapis.com/token
[DEBUG][2024-01-10 13:11:15,456][connectionpool:1052] : Starting new HTTPS connection (1): oauth2.googleapis.com:443
[DEBUG][2024-01-10 13:11:15,554][connectionpool:0546] : https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
[DEBUG][2024-01-10 13:11:15,557][connectionpool:1052] : Starting new HTTPS connection (1): bigquery.googleapis.com:443
[DEBUG][2024-01-10 13:11:16,044][connectionpool:0546] : https://bigquery.googleapis.com:443 "POST /bigquery/v2/projects/team-week-10/datasets?prettyPrint=false HTTP/1.1" 200 None
[INFO ][2024-01-10 13:11:16,045][3044943226:0008] : Created dataset: team-week-10:nfl_sports_betting

In [17]:
import uuid
import numpy as np
df = pd.read_csv("./spreadspoke_scores.csv", header=0)

df = df[df["schedule_season"] > 1978]


df['uuid'] = [uuid.uuid4() for _ in range(len(df.index))]
df = df.astype({"uuid": "string"})


games_df = df.drop(columns=["weather_detail", "stadium_neutral", "over_under_line", "spread_favorite", "team_favorite_id"])

games_df.dropna(subset=["score_home", "score_away"], inplace=True)


games_df = games_df.rename(columns={"weather_humidity": "humidity_%", "weather_wind_mph": "wind_mph", "weather_temperature": "temperature_F", "schedule_date": "date", "schedule_season": "season", "schedule_week": "week", "schedule_playoff": "playoff"})

games_df["date"] = pd.to_datetime(games_df["date"])

games_df = games_df.astype({"score_home": int, "score_away": int, "temperature_F": int, "wind_mph": int, "humidity_%": int}, errors="ignore")

display(games_df)
games_df.info()

,date,season,week,playoff,team_home,score_home,score_away,team_away,stadium,temperature_F,wind_mph,humidity_%,uuid
2501,1979-09-01,1979,1,False,Tampa Bay Buccaneers,31,16,Detroit Lions,Houlihan's Stadium,79.0,9.0,87.0,6fd3aca9-263f-42b3-ae84-48137e3f21a6
2502,1979-09-02,1979,1,False,Buffalo Bills,7,9,Miami Dolphins,Ralph Wilson Stadium,74.0,15.0,74.0,bc4277d0-66db-45ba-a891-a090a0dfb39d
2503,1979-09-02,1979,1,False,Chicago Bears,6,3,Green Bay Packers,Soldier Field,78.0,11.0,68.0,42e3f9db-a444-4daa-b577-8f02b4d47abe
2504,1979-09-02,1979,1,False,Denver Broncos,10,0,Cincinnati Bengals,Mile High Stadium,69.0,6.0,38.0,6521ca17-ad56-42d9-a56b-b719dcc6e9ae
2505,1979-09-02,1979,1,False,Kansas City Chiefs,14,0,Baltimore Colts,Arrowhead Stadium,76.0,8.0,71.0,db879614-4003-4bbc-8401-b7e40bb942f3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13751,2023-12-24,2023,16,False,Tampa Bay Buccaneers,30,12,Jacksonville Jaguars,Raymond James Stadium,NaN,NaN,NaN,f6caf8c6-57c2-4524-aa54-1a697313314d
13752,2023-12-24,2023,16,False,Tennessee Titans,17,20,Seattle Seahawks,Nissan Stadium,NaN,NaN,NaN,d6d60846-d139-47c0-b4d0-e03e4f816b23
13753,2023-12-25,2023,16,False,Kansas City Chiefs,14,20,Las Vegas Raiders,GEHA Field at Arrowhead Stadium,NaN,NaN,NaN,070f0a24-6392-4ac1-a066-3187c8b90d9e
13754,2023-12-25,2023,16,False,Philadelphia Eagles,33,25,New York Giants,Lincoln Financial Field,NaN,NaN,NaN,df820ba7-8c68-4583-9b1d-0abe24fc68b5
13755,2023-12-25,2023,16,False,San Francisco 49ers,19,33,Baltimore Ravens,Levi's Stadium,NaN,NaN,NaN,f6225c99-626e-412a-b2fa-1e71124a4d10

<class 'pandas.core.frame.DataFrame'>
Index: 11255 entries, 2501 to 13755
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           11255 non-null  datetime64[ns]
 1   season         11255 non-null  int64
 2   week           11255 non-null  object
 3   playoff        11255 non-null  bool
 4   team_home      11255 non-null  object
 5   score_home     11255 non-null  int64
 6   score_away     11255 non-null  int64
 7   team_away      11255 non-null  object
 8   stadium        11255 non-null  object
 9   temperature_F  10130 non-null  float64
 10  wind_mph       10114 non-null  float64
 11  humidity_%     6358 non-null   float64
 12  uuid           11255 non-null  string
dtypes: bool(1), datetime64[ns](1), float64(3), int64(3), object(4), string(1)
memory usage: 1.1+ MB

In [8]:
games_table_name = f"{PROJECT_NAME}.{DATASET_NAME}.{TABLE_METADATA['games']['table_name']}"
games_schema = schema=TABLE_METADATA['games']['schema']

def load_table(
    df: pd.DataFrame, 
    client: bigquery.Client, 
    table_name: str, 
    schema: List[bigquery.SchemaField], 
    create_disposition: str = 'CREATE_IF_NEEDED', 
    write_disposition: str = 'WRITE_TRUNCATE'
    ) -> None:
    """load dataframe into bigquery table

    Args:
        df (pd.DataFrame): dataframe to load
        client (bigquery.Client): bigquery client
        table_name (str): full table name including project and dataset id
        schema (List[bigquery.SchemaField]): table schema with data types
        create_disposition (str, optional): create table disposition. Defaults to 'CREATE_IF_NEEDED'.
        write_disposition (str, optional): overwrite table disposition. Defaults to 'WRITE_TRUNCATE'.
    """

    # test table name to be full table name including project and dataset name. It must contain to dots
    assert len(table_name.split('.')) == 3, f"Table name must be a full bigquery table name including project and dataset id: '{table_name}'"


    job_config = bigquery.LoadJobConfig(
        create_disposition=create_disposition,
        write_disposition=write_disposition,
        schema=schema
    )
    logger.info(f"loading table: '{table_name}'")
    job = client.load_table_from_dataframe(df, destination=table_name, job_config=job_config)
    job.result() 

    # get the resulting table
    table = client.get_table(table_name)
    logger.info(f"loaded {table.num_rows} rows into {table.full_table_id}")

load_table(games_df, client, games_table_name, games_schema)

[INFO ][2024-01-10 13:20:45,954][898524737:0032] : loading table: 'team-week-10.nfl_sports_betting.dim_games'
[DEBUG][2024-01-10 13:20:46,981][connectionpool:0546] : https://bigquery.googleapis.com:443 "POST /upload/bigquery/v2/projects/team-week-10/jobs?uploadType=multipart HTTP/1.1" 200 2800
[DEBUG][2024-01-10 13:20:47,088][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/4a154ceb-916f-4437-a930-b6d04527e582?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 13:20:47,089][retry:0233] : Retrying due to , sleeping 0.7s ...
[DEBUG][2024-01-10 13:20:47,906][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/4a154ceb-916f-4437-a930-b6d04527e582?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 13:20:47,907][retry:0233] : Retrying due to , sleeping 0.2s ...
[DEBUG][2024-01-10 13:20:48,210][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/4a154ceb-916f-4437-a930-b6d04527e582?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 13:20:48,212][retry:0233] : Retrying due to , sleeping 0.8s ...
[DEBUG][2024-01-10 13:20:49,071][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/4a154ceb-916f-4437-a930-b6d04527e582?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 13:20:49,258][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/datasets/nfl_sports_betting/tables/dim_games?prettyPrint=false HTTP/1.1" 200 None
[INFO ][2024-01-10 13:20:49,259][898524737:0038] : loaded 11255 rows into team-week-10:nfl_sports_betting.dim_games

In [77]:
from google.cloud import bigquery

client = bigquery.Client()
print(f"BigQuery Project: {client.project}")

# list datasets
print("Listing datasets:")

for dataset in client.list_datasets():
    dataset_id = dataset.dataset_id
    print(f"dataset id: `{dataset_id}`, full_name: `{dataset.full_dataset_id}`, labels (tags): {dataset.labels}")

[DEBUG][2024-01-10 16:24:14,373][_default:0255] : Checking /home/jarvismwynn/.creds/jarvis.json for explicit credentials as part of auth process...
[DEBUG][2024-01-10 16:24:14,375][_default:0255] : Checking /home/jarvismwynn/.creds/jarvis.json for explicit credentials as part of auth process...
BigQuery Project: team-week-10
Listing datasets:
[DEBUG][2024-01-10 16:24:14,377][retry:0282] : Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
[DEBUG][2024-01-10 16:24:14,400][requests:0185] : Making request: POST https://oauth2.googleapis.com/token
[DEBUG][2024-01-10 16:24:14,402][connectionpool:1052] : Starting new HTTPS connection (1): oauth2.googleapis.com:443
[DEBUG][2024-01-10 16:24:14,491][connectionpool:0546] : https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
[DEBUG][2024-01-10 16:24:14,494][connectionpool:1052] : Starting new HTTPS connection (1): bigquery.googleapis.com:443
[DEBUG][2024-01-10 16:24:14,748][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/datasets?prettyPrint=false HTTP/1.1" 200 None
dataset id: `nfl_sports_betting`, full_name: `team-week-10:nfl_sports_betting`, labels (tags): {}

In [91]:
df = df[df["schedule_season"] > 1978]
df.dropna(subset=["score_home", "score_away"], inplace=True)

over_under_df = df[["uuid", "over_under_line", "team_favorite_id", "team_home", "score_home", "score_away", "team_away"]]
# display(over_under_df.head(3))

def total_score(df):
    for _ in range(len(df.index)):
        df["total_score"] = df["score_home"] + df["score_away"]
    return df
total_score(over_under_df)

/tmp/ipykernel_157788/2338800694.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["total_score"] = df["score_home"] + df["score_away"]

,uuid,over_under_line,team_favorite_id,team_home,score_home,score_away,team_away,total_score
2501,6fd3aca9-263f-42b3-ae84-48137e3f21a6,30,TB,Tampa Bay Buccaneers,31.0,16.0,Detroit Lions,47.0
2502,bc4277d0-66db-45ba-a891-a090a0dfb39d,39,MIA,Buffalo Bills,7.0,9.0,Miami Dolphins,16.0
2503,42e3f9db-a444-4daa-b577-8f02b4d47abe,31,CHI,Chicago Bears,6.0,3.0,Green Bay Packers,9.0
2504,6521ca17-ad56-42d9-a56b-b719dcc6e9ae,31.5,DEN,Denver Broncos,10.0,0.0,Cincinnati Bengals,10.0
2505,db879614-4003-4bbc-8401-b7e40bb942f3,37,KC,Kansas City Chiefs,14.0,0.0,Baltimore Colts,14.0
...,...,...,...,...,...,...,...,...
13751,f6caf8c6-57c2-4524-aa54-1a697313314d,43,JAX,Tampa Bay Buccaneers,30.0,12.0,Jacksonville Jaguars,42.0
13752,d6d60846-d139-47c0-b4d0-e03e4f816b23,42,SEA,Tennessee Titans,17.0,20.0,Seattle Seahawks,37.0
13753,070f0a24-6392-4ac1-a066-3187c8b90d9e,40.5,KC,Kansas City Chiefs,14.0,20.0,Las Vegas Raiders,34.0
13754,df820ba7-8c68-4583-9b1d-0abe24fc68b5,41.5,PHI,Philadelphia Eagles,33.0,25.0,New York Giants,58.0
13755,f6225c99-626e-412a-b2fa-1e71124a4d10,47.5,SF,San Francisco 49ers,19.0,33.0,Baltimore Ravens,52.0

In [95]:
over_under_df = over_under_df.astype({"score_home": int, "score_away": int, "over_under_line": float, "total_score": int}, errors="ignore")

over_under_df["over_under_line"] = pd.to_numeric(over_under_df["over_under_line"], errors="coerce")

for _ in range(len(over_under_df.index)):
    over_under_df["over"] = over_under_df["total_score"] > over_under_df["over_under_line"]
        # over_under_df["total_score"] == over_under_df["over_under_line"]
        
over_under_df = over_under_df.reset_index(drop=True)

display(over_under_df)
over_under_df.info()

,uuid,over_under_line,team_favorite_id,team_home,score_home,score_away,team_away,total_score,over
0,6fd3aca9-263f-42b3-ae84-48137e3f21a6,30.0,TB,Tampa Bay Buccaneers,31,16,Detroit Lions,47,True
1,bc4277d0-66db-45ba-a891-a090a0dfb39d,39.0,MIA,Buffalo Bills,7,9,Miami Dolphins,16,False
2,42e3f9db-a444-4daa-b577-8f02b4d47abe,31.0,CHI,Chicago Bears,6,3,Green Bay Packers,9,False
3,6521ca17-ad56-42d9-a56b-b719dcc6e9ae,31.5,DEN,Denver Broncos,10,0,Cincinnati Bengals,10,False
4,db879614-4003-4bbc-8401-b7e40bb942f3,37.0,KC,Kansas City Chiefs,14,0,Baltimore Colts,14,False
...,...,...,...,...,...,...,...,...,...
11250,f6caf8c6-57c2-4524-aa54-1a697313314d,43.0,JAX,Tampa Bay Buccaneers,30,12,Jacksonville Jaguars,42,False
11251,d6d60846-d139-47c0-b4d0-e03e4f816b23,42.0,SEA,Tennessee Titans,17,20,Seattle Seahawks,37,False
11252,070f0a24-6392-4ac1-a066-3187c8b90d9e,40.5,KC,Kansas City Chiefs,14,20,Las Vegas Raiders,34,False
11253,df820ba7-8c68-4583-9b1d-0abe24fc68b5,41.5,PHI,Philadelphia Eagles,33,25,New York Giants,58,True
11254,f6225c99-626e-412a-b2fa-1e71124a4d10,47.5,SF,San Francisco 49ers,19,33,Baltimore Ravens,52,True

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11255 entries, 0 to 11254
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uuid              11255 non-null  string
 1   over_under_line   11193 non-null  float64
 2   team_favorite_id  11255 non-null  object
 3   team_home         11255 non-null  object
 4   score_home        11255 non-null  int64
 5   score_away        11255 non-null  int64
 6   team_away         11255 non-null  object
 7   total_score       11255 non-null  int64
 8   over              11255 non-null  bool
dtypes: bool(1), float64(1), int64(3), object(3), string(1)
memory usage: 714.6+ KB

In [100]:
over_under_table_name = f"{PROJECT_NAME}.{DATASET_NAME}.{TABLE_METADATA['over_under']['table_name']}"
over_under_schema = schema=TABLE_METADATA['over_under']['schema']

load_table(over_under_df, client, over_under_table_name, over_under_schema)

[INFO ][2024-01-10 16:38:07,577][898524737:0032] : loading table: 'team-week-10.nfl_sports_betting.fct_over_under'
[DEBUG][2024-01-10 16:38:08,589][connectionpool:0546] : https://bigquery.googleapis.com:443 "POST /upload/bigquery/v2/projects/team-week-10/jobs?uploadType=multipart HTTP/1.1" 200 2356
[DEBUG][2024-01-10 16:38:08,707][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/6310aab4-26ab-48b6-b094-33a400fbfe4c?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 16:38:08,708][retry:0233] : Retrying due to , sleeping 0.6s ...
[DEBUG][2024-01-10 16:38:09,448][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/6310aab4-26ab-48b6-b094-33a400fbfe4c?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 16:38:09,449][retry:0233] : Retrying due to , sleeping 0.8s ...
[DEBUG][2024-01-10 16:38:10,422][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/jobs/6310aab4-26ab-48b6-b094-33a400fbfe4c?location=US&prettyPrint=false HTTP/1.1" 200 None
[DEBUG][2024-01-10 16:38:10,589][connectionpool:0546] : https://bigquery.googleapis.com:443 "GET /bigquery/v2/projects/team-week-10/datasets/nfl_sports_betting/tables/fct_over_under?prettyPrint=false HTTP/1.1" 200 None
[INFO ][2024-01-10 16:38:10,590][898524737:0038] : loaded 11255 rows into team-week-10:nfl_sports_betting.fct_over_under